### ISSUE TITLE
Fetch does not have to fail with a 401

### ISSUE THREAD

**Issue by ylebre** [SimplyEdit/SimplyPresent#1]
This line should not check for a 401:

https://github.com/SimplyEdit/SimplyPresent/blob/aea5c6bc4f897c8e35d6ea43e43c8e0a5008a281/src/base-components/solid/headHtml/solid.html#L7

Instead it should be ok to check for !response.ok instead.

**Comment by poef** [comment]
fetch now checks for response.ok, if not ok and status is 401,402 or 403, it retries with solid-auth-fetcher.
